# 头部菜单，title: link
menu:
  首页: http://dumboj.top
  分类: /categories
  归档: /archives
  标签云: /tagcloud
  关于: /About
  Github: https://github.com/DumboJ

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3: 
  - http://sc1.111ttt.cn/2015/1/06/02/99021925549.mp3
  - http://link.hhtjim.com/qq/001faIUs4M2zna.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: /img/nink.jpg

# 默认文章封面图
cover: /img/mainpage.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    enable: true
    # 是否自动展开评论框
    autoExpand: false
    githubID: DumboJ
    # 应用编号
    clientID: '46c465b787a3b9347cd6'
    # 应用秘钥
    clientSecret: 'ca94721c3c4ac708ed575bb8aabe0a335ebcddcc'
    # issue仓库名
    repo: 'DumboJ.github.io'
    # Github名
    owner: 'DumboJ'
    # Github名
    admin: ['DumboJ']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: true

# 网站关键字
keywords: DumboJ

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
